image:
- Visual Studio 2017
#- Ubuntu  # appveyor broken import lzma (also ubuntu1804) use azure instead.

stack: python 3.7

environment:
  PY_DIR: C:\Python37-x64
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- cmd: set PATH=%MINGW_DIR%;%PATH%

install: pip install -e .[tests]

test_script: pytest -r a -v

