language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

os:
- linux

before_install:
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/
- pip install meson

install: pip install -e .[tests,lint]

script:
- pytest -r a -v
- flake8
- mypy .
